/**
 * vinimay
 * Vinimay is a decentralised social network focused on giving back control of its data to the user
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Post {
    /**
     * Post creation timestamp
     */
    creationTs: number;

    /**
     * Last modification timestamp (equals to the creation timestamp if the post has never been edited)
     */
    lastEditTs: number;

    /**
     * Post author (using the `username@instanceurl.tld` format)
     */
    author: string;

    /**
     * Post content
     */
    content: string;

    /**
     * Post privacy setting ()
     */
    privacy: Post.PrivacyEnum;

    comments: number;

    reactions: number;

}
export namespace Post {
    export enum PrivacyEnum {
        Public = <any> 'public',
        Private = <any> 'private',
        Friends = <any> 'friends'
    }
}
